### ISSUE TITLE
Can't install license version 1.0.0 and up

### ISSUE THREAD

**Issue by philnash** [Ovyerus/license#2]
When trying to install or use license via npx I get the following error message

```
npm i license
npm WARN project-name@1.0.0 No description
npm WARN project-name@1.0.0 No repository field.

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/pnash/projects/project-name/node_modules/license/dist/cli/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/pnash/projects/project-name/node_modules/license/dist/cli/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pnash/.npm/_logs/2020-03-24T03_59_10_214Z-debug.log
```

Version 0.0.3 still works. Was the project released without building the files to `dist`? Or are the `dist` files not being included in the package?

Thanks

**Comment by Ovyerus** [comment]
Hmm, looks like dist does exist, but for some reason its only got `getLicense` in it, none of the CLI stuff. Oops.

I'll see and try to resolve it later this week, thanks for reporting this.

**Comment by Ovyerus** [comment]
And by later this week I mean now I guess. `1.0.2` should fix this, simply forgot to add dist to the `files` array. Oops.

**Comment by philnash** [comment]
Thanks for the quick fix! :+1:

**Comment by Ovyerus** [comment]
No problem!
